services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - sqlvolume:/var/lib/mysql
    networks:
      - ktx-network

  ktx-fe:
    build:
      context: ./ktx-fe
      dockerfile: Dockerfile
    ports:
      - "4300:4300"
    depends_on:
      - ktx-be
    networks:
      - ktx-network

  ktx-be:
    build:
      context: ./ktx-be
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=development
    depends_on:
      - db
    networks:
      - ktx-network
    restart: on-failure

networks:
  ktx-network:

volumes:
  sqlvolume:
